// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY5m2ebozCrIwdifVhQeoFrBwxjNk_f5s',
    appId: '1:689295844787:web:c1cf41cc42c842052057c6',
    messagingSenderId: '689295844787',
    projectId: 'securisalary',
    authDomain: 'securisalary.firebaseapp.com',
    databaseURL:
        'https://securisalary-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'securisalary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN14sbM4DBYkBrWW01Rfcaxzj6E9us0Kk',
    appId: '1:689295844787:android:e1f34fed50e08eca2057c6',
    messagingSenderId: '689295844787',
    projectId: 'securisalary',
    databaseURL:
        'https://securisalary-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'securisalary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7mDqO4KUiY3RmRSEQ391_40C_2cfQ0yA',
    appId: '1:689295844787:ios:e3b933b63449946f2057c6',
    messagingSenderId: '689295844787',
    projectId: 'securisalary',
    databaseURL:
        'https://securisalary-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'securisalary.appspot.com',
    iosBundleId: 'salary.securitas.salarySecuritas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7mDqO4KUiY3RmRSEQ391_40C_2cfQ0yA',
    appId: '1:689295844787:ios:e3b933b63449946f2057c6',
    messagingSenderId: '689295844787',
    projectId: 'securisalary',
    databaseURL:
        'https://securisalary-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'securisalary.appspot.com',
    iosBundleId: 'salary.securitas.salarySecuritas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY5m2ebozCrIwdifVhQeoFrBwxjNk_f5s',
    appId: '1:689295844787:web:69ba350325601f1e2057c6',
    messagingSenderId: '689295844787',
    projectId: 'securisalary',
    authDomain: 'securisalary.firebaseapp.com',
    databaseURL:
        'https://securisalary-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'securisalary.appspot.com',
  );
}
